services:
    settings_manager:
        class: Dmishh\Bundle\SettingsBundle\Manager\SettingsManager
        arguments:
            - @doctrine.orm.entity_manager
            - %settings_manager.settings%

    form.type.settings:
        class: Dmishh\Bundle\SettingsBundle\Form\Type\SettingsType
        arguments: [%settings_manager.settings%]
        tags:
            - { name: form.type, alias: dmishh_settings }
