services:
    dmishh_settings.manager:
        class: Dmishh\Bundle\SettingsBundle\Manager\SettingsManager
        arguments:
            - @doctrine.orm.entity_manager
            - { settings_configuration: %dmishh_settings.manager.settings% }

    form.type.dmishh_settings:
        class: Dmishh\Bundle\SettingsBundle\Form\Type\SettingsType
        arguments: [%dmishh_settings.manager.settings%]
        tags:
            - { name: form.type, alias: dmishh_settings }

    form.type.dmishh_setting:
        class: Dmishh\Bundle\SettingsBundle\Form\Type\SettingType
        tags:
            - { name: form.type, alias: dmishh_setting }
